### ISSUE TITLE
Add built-in filter function for every Avro class

### ISSUE THREAD

**Issue by kostja** [tarantool/graphql.0#13]
like()
regexp()
>
<
or
and

**Comment by Totktonada** [comment]
Plan:

- parsing of a filter (string or input object?)
- pcre
- eq, ne, lt, gt, le, ge
- and, or, not
- speedup using indexes

**Comment by Totktonada** [comment]
More from #43:

* IS NULL / IS NOT NULL

**Comment by Totktonada** [comment]
More from #39:

* [maybe] Support for nested filtering by connection_name.field_name.

**Comment by Totktonada** [comment]
Sink down to prio2 since PCRE support was extracted to #73.

**Comment by Totktonada** [comment]
## Syntax

C-style expressions. Field names (dot-separated for inner fields) of a current
object can be used. Variables can be used.

### Grammar

TBD.

## Overview

Create AST using lulpeg in the compile phase, save it in a query AST.

Set an usage flag for variables in use (to avoid an error re non-used
variable).

Pass the AST to accessor_general within `extra` arguments. Implement a tuple
filtering according by the AST in `process_tuple`.

If no index is found based on filters, offset or from a connection (see
`get_index_name`), then it is worth to use the AST to perform index search.
Basically we need to collect all always-checked predicates (maybe it worth to
construct CNF?): ones that are not under OR operator. Then prioritize it: 
equality first, then less-great. Then attempt to match each predicate against
existing indexes (by a name of the field it operates on). When a match found,
then rewrite AST to avoid redundant operations in `process_tuple` (remove the 
operation that will be performed by an index).

The approach above is very-very basic and cannot handle many cases. But I
think it is on optimal point between efficiency and simplicity for now.

## Follow ups 

### Type checking

Each operation argument should have set of allowed types. Say, 'number' for a
+, -, <, >, 'boolean' for ||, &&, !, 'number' and 'string' for == and != as
well as a type of result.

A root expression must have the boolean type, because it will be used as the 
predicate todecided whether an object should be filtered in. 

It seems that we should take care of nullability of a type: say, `regexp` will
not work with null as an argument, but `is_null` will do.

### Functions

E. g. regexp(<pattern: string expr>, <string expr>).

### IS NULL / IS NOT NULL operations

is_null(<expr>)
is_not_null(<expr>)
