### ISSUE TITLE
Support vshard

### ISSUE THREAD

**Issue by Totktonada** [tarantool/graphql.0#181]

**Comment by Khatskevich** [comment]
Due to the nature of the `vshard` we have to extend the graphql schema description format:
1. Add `pk` -> `bucket_id` function.
2. Point out that the connection leads to an object at the same bucket.

# Api change proposals

## pk -> bucket_id
Add `buchet_map` field to a collection  which has the following format:
```
{
    function_name = "fname", -- this function is specified in accessor
    args = {"farg_1", "farg_2" ... }, -- arguments to the function 
}
```

## Same bucket
Add `replicaset_preserved` option to a connection (which means that connection leads to an object which is stored on the same server)

**Comment by Totktonada** [comment]
The customer integrates vshard in its own way on its side, so the priority of this task is sinked down.

**Comment by Totktonada** [comment]
I'm going to archive the repository. I'll proceed as follows:

* Mark all open pull requests with the `archived` label and close.
* Mark all open issues with `archived` and `wontfix` labels and close.
* Archive the repository.

Consider the following projects:

* https://github.com/tarantool/graphql
* https://github.com/tarantool/graphqlapi
* https://github.com/tarantool/graphqlide
