### ISSUE TITLE
Optimize is_index_exists for shard

### ISSUE THREAD

**Issue by Khatskevich** [tarantool/graphql.0#206]
`is_index_exists` performs a very long scan over all nodes.
However, it seems like this function is very frequently called.

Solutions:
1. Cache results.
2. Suppose that all indexes exist by default (and catch errors during iteration).

I am for the second option.

**Comment by Totktonada** [comment]
I'm against relaxing our constraints w/o a really significant reason. Can you, please, benchmark w/ `is_index_exists` and w/o on existing benchmarks w/o artificial delay (`tc qdisc del dev lo root`) and with 1ms rtt (`tc qdisc add dev lo root handle 1:0 netem delay 0.5msec`) and post results here? I think 4 storage nodes is enough to observe an order of improvement.

Maybe we should check that omitting this check gives understandable error? If so, I'm will not against the removing. Test on that is needed. Maybe if the error is not good we should provide stored procedure to make it right.

The feature of checking consistency btw storages is good, IMHO. But we can perform it once before all requests.

**Comment by Totktonada** [comment]
`is_index_exists` does not perform a network request. It looks at net.box space object fields locally. Benchmarked without artificial delay and with rtt 1ms, the difference within the noise.

@Khatskevich can we close the issue?

**Comment by Khatskevich** [comment]
Yes. That is not a remote call.
Possibly it should be closed.
The check on each fetch is redundant though.

**Comment by Totktonada** [comment]
I’m kinda afraid of possibility of a subtle inconsistent state that leads a software to work in unexpected way without any visible reason for it (on the first glance, at least). A cluster software is especially complicated in operations. So I prefer to leave a cluster consistency check where it is easy and cheap to give an operation team a message despite the fact that we are not responsible on cluster configuration problems. I just feels safer in the case.

Decided to leave `is_index_exists` check, because it does not lead to any known problems.

Please, feel free to introduce (or file an issue on it) the separate consistency check stage (maybe as a separate graphql method, say, graphql:check()) if you think it will looks a way better. We can check all collections and indexes against the ones provided in the graphql configuration within the stage.
