### ISSUE TITLE
Add a support of indexes by service fields

### ISSUE THREAD

**Issue by Kasen** [tarantool/graphql.0#51]
We can add indexes only by schema fields now.

**Comment by Totktonada** [comment]
The case is the following: there is a field of an object that is declared as a part of one of indexes, but the real index part is by a service field with the same value, but converted into an another type.

So, the trick with using the field from an object in metainfo and the corr. service field in the real index info does not work when the types is different.

We need some mechanics to preprocess a value passed to the `index:pairs()`, I think.

**Comment by Totktonada** [comment]
Hmm… we can use 'different meta and index' trick and preprocess values passed to the `index:pairs()` in `graphql/accessor_{space,shard}.lua`, inside `pairs` metamethod. @Kasen, can you check it met your needs? I see it like that:

```
diff --git a/graphql/accessor_shard.lua b/graphql/accessor_shard.lua
index 5b3c613..623d8e3 100644
--- a/graphql/accessor_shard.lua
+++ b/graphql/accessor_shard.lua
@@ -59,6 +59,11 @@ local function get_index(collection_name, index_name)
             pairs = function(self, value, opts)
                 local opts = opts or {}
                 opts.limit = opts.limit or LIMIT
+                if collection_name == 'very_specific_space' and
+                        (index_name == 0 or index_name == 'id') then
+                    value = table.copy(value)
+                    value[1] = tonumber(value[1])
+                end
                 local tuples = shard:secondary_select(collection_name,
                     index_name, opts, value, 0)
                 local cur = 1
```

By the way, you can use opts argument for any options you want to pass to that iterator from accessor_general part (don’t sure why, just FYI).

**Comment by Totktonada** [comment]
@Kasen says the propsed hack fit its needs. We add explicit way to redefine any of accessor_{space,shard} functions and have consensus that it is better to just redefine `get_index` / `get_primary_index` for implementing of such specific cases (instead of having `convert_value_before_pass_to_index` function in public API).

So, I think the issue can be closed.

Also we discussed how we should react on a non-existent field in a query: give an error or return empty list (in context of requests in several schema versions on data of several versions). We have consensus that giving an error is right behaviour (moreover, such query does not fit schema and cannot be compiled) and custom flatten must always return an object in appropriate version (exactly as graphql expects). So we have right behaviour in the graphql library.
